apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp
spec:
  selector:
    matchLabels:
      app: nlp
      env: prod
  replicas: 2
  template:
    metadata:
      labels:
        app: nlp
        env: prod
    spec:
      containers:
        - name: nlp
          image: 788332838494.dkr.ecr.us-east-1.amazonaws.com/nlp-service-fargate:latest
          envFrom:
            - configMapRef:
                name: nlp-config
          ports:
            - containerPort: 9000
              name: http-server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hc
              port: http-server
              httpHeaders:
                - name: host
                  value: nlp
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
