apiVersion: v1
kind: Service
metadata:
  name: nlp
  labels:
    app: nlp
    env: prod
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http-server
  selector:
    app: nlp
    env: prod
