apiVersion: batch/v1
kind: Job
metadata:
  name: migrant
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: migrant
        env: prod
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrant
          image: 788332838494.dkr.ecr.us-east-1.amazonaws.com/migrant:0.1.1
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: migrant-matchvote-db

