apiVersion: batch/v1
kind: Job
metadata:
  name: almanack
spec:
  template:
    metadata:
      labels:
        app: almanack
        env: prod
    spec:
      restartPolicy: OnFailure
      containers:
      - name: almanack
        image: 788332838494.dkr.ecr.us-east-1.amazonaws.com/almanack:0.1.0
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: almanack-secrets
